In [1]:
import pandas as pd

In [2]:
numbers = pd.Series([10, 20, 30, 40])
print(numbers)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
numbers = pd.Series([10, 20, 30, 40])
print(numbers)

In [4]:
numbers = pd.Series([10, 20, 30, 40])
print(numbers)

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
np.zeros((2,3))      # Array of zeros
np.ones((2,3))       # Array of ones
np.eye(3)            # Identity matrix
np.arange(1,10,2)    # Sequence
np.linspace(0,1,5)   # Evenly spaced values

NameError: name 'np' is not defined

In [6]:
student = {
   "Name": ["Ali", "Sara", "Ahmed"],
   "Age": [20, 21, 19],
   "Marks": [90, 88, 95]
}

In [7]:
df = pd.DataFrame(student)

print(df)

    Name  Age  Marks
0    Ali   20     90
1   Sara   21     88
2  Ahmed   19     95

In [3]:
import pandas as pd

students = {
    "ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Bilal", "Fatima", "Hassan", "Maryam", "Usman", "Zainab"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 22, 20, 21],
    "Department": ["AI", "CS", "SE", "AI", "CS", "AI", "SE", "CS", "AI", "SE"],
    "Marks": [85, 90, 78, 95, 67, 88, 73, 81, 92, 86],
    "City": ["Gilgit", "Islamabad", "Hunza", "Lahore", "Karachi", "Gilgit", "Rawalpindi", "Skardu", "Hunza", "Gilgit"],
    "Attendance": [92, 95, 88, 98, 80, 91, 84, 89, 96, 93]
}

df = pd.DataFrame(students)

print(df)

    ID    Name  Age Department  Marks        City  Attendance
0  101     Ali   20         AI     85      Gilgit          92
1  102    Sara   21         CS     90   Islamabad          95
2  103   Ahmed   19         SE     78       Hunza          88
3  104  Ayesha   22         AI     95      Lahore          98
4  105   Bilal   20         CS     67     Karachi          80
5  106  Fatima   21         AI     88      Gilgit          91
6  107  Hassan   23         SE     73  Rawalpindi          84
7  108  Maryam   22         CS     81      Skardu          89
8  109   Usman   20         AI     92       Hunza          96
9  110  Zainab   21         SE     86      Gilgit          93

In [13]:
students = {
    "ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Bilal", "Fatima", "Hassan", "Maryam", "Usman", "Zainab"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 22, 20, 21],
    "Department": ["AI", "CS", "SE", "AI", "CS", "AI", "SE", "CS", "AI", "SE"],
    "Marks": [85, 90, 78, 95, 67, 88, 73, 81, 92, 86],
    "City": ["Gilgit", "Islamabad", "Hunza", "Lahore", "Karachi", "Gilgit", "Rawalpindi", "Skardu", "Hunza", "Gilgit"],
    "Attendance": [92, 95, 88, 98, 80, 91, 84, 89, 96, 93]
}

df = pd.DataFrame(students)

print(df)

    ID    Name  Age Department  Marks        City  Attendance
0  101     Ali   20         AI     85      Gilgit          92
1  102    Sara   21         CS     90   Islamabad          95
2  103   Ahmed   19         SE     78       Hunza          88
3  104  Ayesha   22         AI     95      Lahore          98
4  105   Bilal   20         CS     67     Karachi          80
5  106  Fatima   21         AI     88      Gilgit          91
6  107  Hassan   23         SE     73  Rawalpindi          84
7  108  Maryam   22         CS     81      Skardu          89
8  109   Usman   20         AI     92       Hunza          96
9  110  Zainab   21         SE     86      Gilgit          93

In [5]:
print(df.head())

    ID    Name  Age Department  Marks       City  Attendance
0  101     Ali   20         AI     85     Gilgit          92
1  102    Sara   21         CS     90  Islamabad          95
2  103   Ahmed   19         SE     78      Hunza          88
3  104  Ayesha   22         AI     95     Lahore          98
4  105   Bilal   20         CS     67    Karachi          80

In [6]:
print(df.head(2))

    ID  Name  Age Department  Marks       City  Attendance
0  101   Ali   20         AI     85     Gilgit          92
1  102  Sara   21         CS     90  Islamabad          95

In [12]:
print(df.tail())

    ID    Name  Age Department  Marks        City  Attendance
5  106  Fatima   21         AI     88      Gilgit          91
6  107  Hassan   23         SE     73  Rawalpindi          84
7  108  Maryam   22         CS     81      Skardu          89
8  109   Usman   20         AI     92       Hunza          96
9  110  Zainab   21         SE     86      Gilgit          93

In [13]:
print(df.describe())

              ID        Age      Marks  Attendance
count   10.00000  10.000000  10.000000   10.000000
mean   105.50000  20.900000  83.500000   90.600000
std      3.02765   1.197219   8.784456    5.541761
min    101.00000  19.000000  67.000000   80.000000
25%    103.25000  20.000000  78.750000   88.250000
50%    105.50000  21.000000  85.500000   91.500000
75%    107.75000  21.750000  89.500000   94.500000
max    110.00000  23.000000  95.000000   98.000000

In [14]:
print(df.columns)

Index(['ID', 'Name', 'Age', 'Department', 'Marks', 'City', 'Attendance'], dtype='str')

In [15]:
print(df.columns)

Index(['ID', 'Name', 'Age', 'Department', 'Marks', 'City', 'Attendance'], dtype='str')

In [19]:
print(df.iloc[4])

ID                105
Name            Bilal
Age                20
Department         CS
Marks              67
City          Karachi
Attendance         80
Name: 4, dtype: object

In [20]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Marks', 'City', 'Attendance'], dtype='str')

In [22]:
df.loc[4,['Marks']]=33

In [23]:
print(df.iloc[4])

ID                105
Name            Bilal
Age                20
Department         CS
Marks              33
City          Karachi
Attendance         80
Name: 4, dtype: object

In [27]:
df.drop(1)

    ID    Name  Age Department  Marks        City  Attendance
0  101     Ali   20         AI     85      Gilgit          92
2  103   Ahmed   19         SE     78       Hunza          88
3  104  Ayesha   22         AI     95      Lahore          98
4  105   Bilal   20         CS     33     Karachi          80
5  106  Fatima   21         AI     88      Gilgit          91
6  107  Hassan   23         SE     73  Rawalpindi          84
7  108  Maryam   22         CS     81      Skardu          89
8  109   Usman   20         AI     92       Hunza          96
9  110  Zainab   21         SE     86      Gilgit          93

In [29]:
df.sort_values('Marks', ascending=True)

    ID    Name  Age Department  Marks        City  Attendance
4  105   Bilal   20         CS     33     Karachi          80
6  107  Hassan   23         SE     73  Rawalpindi          84
2  103   Ahmed   19         SE     78       Hunza          88
7  108  Maryam   22         CS     81      Skardu          89
0  101     Ali   20         AI     85      Gilgit          92
9  110  Zainab   21         SE     86      Gilgit          93
5  106  Fatima   21         AI     88      Gilgit          91
1  102    Sara   21         CS     90   Islamabad          95
8  109   Usman   20         AI     92       Hunza          96
3  104  Ayesha   22         AI     95      Lahore          98